/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CaiDatRouteImport } from './routes/cai-dat'
import { Route as DangKyRouteImport } from './routes/dang-ky'
import { Route as DangNhapRouteImport } from './routes/dang-nhap'
import { Route as GuiHoSoRouteImport } from './routes/gui-ho-so'
import { Route as TaiKhoanRouteImport } from './routes/tai-khoan'
import { Route as TroGiupRouteImport } from './routes/tro-giup'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminDanhGiaRouteImport } from './routes/admin.danh-gia'
import { Route as AdminKnowledgeStudioRouteImport } from './routes/admin.knowledge-studio'
import { Route as AdminPhanHoiRouteImport } from './routes/admin.phan-hoi'
import { Route as AdminPhanQuyenRouteImport } from './routes/admin.phan-quyen'
import { Route as AdminToChucRouteImport } from './routes/admin.to-chuc'
import { Route as AdminTuanThuRouteImport } from './routes/admin.tuan-thu'
import { Route as HoSoIndexRouteImport } from './routes/ho-so.index'
import { Route as HoSoIdRouteImport } from './routes/ho-so.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaiDatRoute = CaiDatRouteImport.update({
  id: '/cai-dat',
  path: '/cai-dat',
  getParentRoute: () => rootRouteImport,
} as any)
const DangKyRoute = DangKyRouteImport.update({
  id: '/dang-ky',
  path: '/dang-ky',
  getParentRoute: () => rootRouteImport,
} as any)
const DangNhapRoute = DangNhapRouteImport.update({
  id: '/dang-nhap',
  path: '/dang-nhap',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiHoSoRoute = GuiHoSoRouteImport.update({
  id: '/gui-ho-so',
  path: '/gui-ho-so',
  getParentRoute: () => rootRouteImport,
} as any)
const TaiKhoanRoute = TaiKhoanRouteImport.update({
  id: '/tai-khoan',
  path: '/tai-khoan',
  getParentRoute: () => rootRouteImport,
} as any)
const TroGiupRoute = TroGiupRouteImport.update({
  id: '/tro-giup',
  path: '/tro-giup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDanhGiaRoute = AdminDanhGiaRouteImport.update({
  id: '/admin/danh-gia',
  path: '/admin/danh-gia',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKnowledgeStudioRoute = AdminKnowledgeStudioRouteImport.update({
  id: '/admin/knowledge-studio',
  path: '/admin/knowledge-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPhanHoiRoute = AdminPhanHoiRouteImport.update({
  id: '/admin/phan-hoi',
  path: '/admin/phan-hoi',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPhanQuyenRoute = AdminPhanQuyenRouteImport.update({
  id: '/admin/phan-quyen',
  path: '/admin/phan-quyen',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminToChucRoute = AdminToChucRouteImport.update({
  id: '/admin/to-chuc',
  path: '/admin/to-chuc',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTuanThuRoute = AdminTuanThuRouteImport.update({
  id: '/admin/tuan-thu',
  path: '/admin/tuan-thu',
  getParentRoute: () => rootRouteImport,
} as any)
const HoSoIndexRoute = HoSoIndexRouteImport.update({
  id: '/ho-so/',
  path: '/ho-so/',
  getParentRoute: () => rootRouteImport,
} as any)
const HoSoIdRoute = HoSoIdRouteImport.update({
  id: '/ho-so/$id',
  path: '/ho-so/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cai-dat': typeof CaiDatRoute
  '/dang-ky': typeof DangKyRoute
  '/dang-nhap': typeof DangNhapRoute
  '/gui-ho-so': typeof GuiHoSoRoute
  '/tai-khoan': typeof TaiKhoanRoute
  '/tro-giup': typeof TroGiupRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/danh-gia': typeof AdminDanhGiaRoute
  '/admin/knowledge-studio': typeof AdminKnowledgeStudioRoute
  '/admin/phan-hoi': typeof AdminPhanHoiRoute
  '/admin/phan-quyen': typeof AdminPhanQuyenRoute
  '/admin/to-chuc': typeof AdminToChucRoute
  '/admin/tuan-thu': typeof AdminTuanThuRoute
  '/ho-so/$id': typeof HoSoIdRoute
  '/admin/': typeof AdminIndexRoute
  '/ho-so/': typeof HoSoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cai-dat': typeof CaiDatRoute
  '/dang-ky': typeof DangKyRoute
  '/dang-nhap': typeof DangNhapRoute
  '/gui-ho-so': typeof GuiHoSoRoute
  '/tai-khoan': typeof TaiKhoanRoute
  '/tro-giup': typeof TroGiupRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/danh-gia': typeof AdminDanhGiaRoute
  '/admin/knowledge-studio': typeof AdminKnowledgeStudioRoute
  '/admin/phan-hoi': typeof AdminPhanHoiRoute
  '/admin/phan-quyen': typeof AdminPhanQuyenRoute
  '/admin/to-chuc': typeof AdminToChucRoute
  '/admin/tuan-thu': typeof AdminTuanThuRoute
  '/ho-so/$id': typeof HoSoIdRoute
  '/admin': typeof AdminIndexRoute
  '/ho-so': typeof HoSoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cai-dat': typeof CaiDatRoute
  '/dang-ky': typeof DangKyRoute
  '/dang-nhap': typeof DangNhapRoute
  '/gui-ho-so': typeof GuiHoSoRoute
  '/tai-khoan': typeof TaiKhoanRoute
  '/tro-giup': typeof TroGiupRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/danh-gia': typeof AdminDanhGiaRoute
  '/admin/knowledge-studio': typeof AdminKnowledgeStudioRoute
  '/admin/phan-hoi': typeof AdminPhanHoiRoute
  '/admin/phan-quyen': typeof AdminPhanQuyenRoute
  '/admin/to-chuc': typeof AdminToChucRoute
  '/admin/tuan-thu': typeof AdminTuanThuRoute
  '/ho-so/$id': typeof HoSoIdRoute
  '/admin/': typeof AdminIndexRoute
  '/ho-so/': typeof HoSoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cai-dat'
    | '/dang-ky'
    | '/dang-nhap'
    | '/gui-ho-so'
    | '/tai-khoan'
    | '/tro-giup'
    | '/admin/audit'
    | '/admin/danh-gia'
    | '/admin/knowledge-studio'
    | '/admin/phan-hoi'
    | '/admin/phan-quyen'
    | '/admin/to-chuc'
    | '/admin/tuan-thu'
    | '/ho-so/$id'
    | '/admin/'
    | '/ho-so/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cai-dat'
    | '/dang-ky'
    | '/dang-nhap'
    | '/gui-ho-so'
    | '/tai-khoan'
    | '/tro-giup'
    | '/admin/audit'
    | '/admin/danh-gia'
    | '/admin/knowledge-studio'
    | '/admin/phan-hoi'
    | '/admin/phan-quyen'
    | '/admin/to-chuc'
    | '/admin/tuan-thu'
    | '/ho-so/$id'
    | '/admin'
    | '/ho-so'
  id:
    | '__root__'
    | '/'
    | '/cai-dat'
    | '/dang-ky'
    | '/dang-nhap'
    | '/gui-ho-so'
    | '/tai-khoan'
    | '/tro-giup'
    | '/admin/audit'
    | '/admin/danh-gia'
    | '/admin/knowledge-studio'
    | '/admin/phan-hoi'
    | '/admin/phan-quyen'
    | '/admin/to-chuc'
    | '/admin/tuan-thu'
    | '/ho-so/$id'
    | '/admin/'
    | '/ho-so/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaiDatRoute: typeof CaiDatRoute
  DangKyRoute: typeof DangKyRoute
  DangNhapRoute: typeof DangNhapRoute
  GuiHoSoRoute: typeof GuiHoSoRoute
  TaiKhoanRoute: typeof TaiKhoanRoute
  TroGiupRoute: typeof TroGiupRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminDanhGiaRoute: typeof AdminDanhGiaRoute
  AdminKnowledgeStudioRoute: typeof AdminKnowledgeStudioRoute
  AdminPhanHoiRoute: typeof AdminPhanHoiRoute
  AdminPhanQuyenRoute: typeof AdminPhanQuyenRoute
  AdminToChucRoute: typeof AdminToChucRoute
  AdminTuanThuRoute: typeof AdminTuanThuRoute
  HoSoIdRoute: typeof HoSoIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  HoSoIndexRoute: typeof HoSoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cai-dat': {
      id: '/cai-dat'
      path: '/cai-dat'
      fullPath: '/cai-dat'
      preLoaderRoute: typeof CaiDatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dang-ky': {
      id: '/dang-ky'
      path: '/dang-ky'
      fullPath: '/dang-ky'
      preLoaderRoute: typeof DangKyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dang-nhap': {
      id: '/dang-nhap'
      path: '/dang-nhap'
      fullPath: '/dang-nhap'
      preLoaderRoute: typeof DangNhapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gui-ho-so': {
      id: '/gui-ho-so'
      path: '/gui-ho-so'
      fullPath: '/gui-ho-so'
      preLoaderRoute: typeof GuiHoSoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tai-khoan': {
      id: '/tai-khoan'
      path: '/tai-khoan'
      fullPath: '/tai-khoan'
      preLoaderRoute: typeof TaiKhoanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tro-giup': {
      id: '/tro-giup'
      path: '/tro-giup'
      fullPath: '/tro-giup'
      preLoaderRoute: typeof TroGiupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/danh-gia': {
      id: '/admin/danh-gia'
      path: '/admin/danh-gia'
      fullPath: '/admin/danh-gia'
      preLoaderRoute: typeof AdminDanhGiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/knowledge-studio': {
      id: '/admin/knowledge-studio'
      path: '/admin/knowledge-studio'
      fullPath: '/admin/knowledge-studio'
      preLoaderRoute: typeof AdminKnowledgeStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/phan-hoi': {
      id: '/admin/phan-hoi'
      path: '/admin/phan-hoi'
      fullPath: '/admin/phan-hoi'
      preLoaderRoute: typeof AdminPhanHoiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/phan-quyen': {
      id: '/admin/phan-quyen'
      path: '/admin/phan-quyen'
      fullPath: '/admin/phan-quyen'
      preLoaderRoute: typeof AdminPhanQuyenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/to-chuc': {
      id: '/admin/to-chuc'
      path: '/admin/to-chuc'
      fullPath: '/admin/to-chuc'
      preLoaderRoute: typeof AdminToChucRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tuan-thu': {
      id: '/admin/tuan-thu'
      path: '/admin/tuan-thu'
      fullPath: '/admin/tuan-thu'
      preLoaderRoute: typeof AdminTuanThuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ho-so/': {
      id: '/ho-so/'
      path: '/ho-so'
      fullPath: '/ho-so/'
      preLoaderRoute: typeof HoSoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ho-so/$id': {
      id: '/ho-so/$id'
      path: '/ho-so/$id'
      fullPath: '/ho-so/$id'
      preLoaderRoute: typeof HoSoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaiDatRoute: CaiDatRoute,
  DangKyRoute: DangKyRoute,
  DangNhapRoute: DangNhapRoute,
  GuiHoSoRoute: GuiHoSoRoute,
  TaiKhoanRoute: TaiKhoanRoute,
  TroGiupRoute: TroGiupRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminDanhGiaRoute: AdminDanhGiaRoute,
  AdminKnowledgeStudioRoute: AdminKnowledgeStudioRoute,
  AdminPhanHoiRoute: AdminPhanHoiRoute,
  AdminPhanQuyenRoute: AdminPhanQuyenRoute,
  AdminToChucRoute: AdminToChucRoute,
  AdminTuanThuRoute: AdminTuanThuRoute,
  HoSoIdRoute: HoSoIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  HoSoIndexRoute: HoSoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
